BaseURL: "http://daigo2010.github.io/"
LanguageCode: "ja-jp"
Title: "Daigo Suganuma Memorabilia"

Params:
    Author: "Daigo Suganuma"
    Birth: "1981-06-18"
    DateForm: "2006-01-02 15:04"
    GoogleAnalyticsUserID: "UA-68147214-1"
    GravatarHash: "0156aafaae38935e2e520ebc75c82621"
    #Facebook: "Your ID."
    Twitter: "daigo_suga"
    Github: "daigo2010"
    ShowRelatedPost: True
    #Disqus: "."
    SyntaxHighlightTheme: "default.min.css"

Indexes:
    tag: "tags"

permalinks:
    post: /blog/:year/:month/:day/:title/

MetadataFormat: "yaml"
